### ISSUE TITLE
[BUG] Cannot use / freehotels command Always prompt that the hotel category cannot be found

### ISSUE THREAD

**Issue by charmaznable** [TrueMB/RentIt#16]
Cannot use / freehotels command
Always prompt that the hotel category cannot be found
I have set up the hotel category
    HotelCategory:
      1:
        usePermission: false
        autoPaymentDefault: true
        autoPaymentDisabled: false
        maxRentExtendAmount: 5
        disableDoorCommand: false
        ownerBypassLock: true
        doorsClosedUntilBuy: true
        doorsClosedAfterBuy: false
        reminderRentRunningOut: '1D'
  categoryHotel:
    displayName: '&f&l旅店客房类别'
    invSize: 9
    items:
      category1:
        slot: 3
        categoryID: 1
        displayName: '&f&l剑与盾之歌'
        type: CHEST
        lore: {}

**Comment by TrueMB** [comment]
Did you create a categopry with **/<shop/hotel> createCat ...** ?
Otherwise please send me the latest.log

**Comment by charmaznable** [comment]
I've created  a categopry.Moreover, the console did not report errors, and the hotel operated well. Just can't find the category in the command.

**Comment by TrueMB** [comment]
The "hotel category cannot be found" message is getting send, after you click in the /freehotels GUI on the 3rd Item Slot?
Can you send me a Screenshot of **/hotel listcat** and the config as a file or on pastebin? **Without** any database credentials of course.


PS: Thank you really much for the donation!

**Comment by charmaznable** [comment]
You're welcome. Your plug-in is worth my donation.
I'm not an English speaker, so my screenshot is in Chinese.
 This is a screenshot after the command .
![QQ截图20220515001350](https://user-images.githubusercontent.com/40638503/168440051-97eba571-9c26-4206-b7c7-3737cc73bd64.png)
Because I only use the hotel function, I translate the configuration files and hotel related items into Chinese.
 Here is my configuration 
[config.txt](https://github.com/TrueMB/RentIt/files/8693510/config.txt)

**Comment by TrueMB** [comment]
Found the Bug in my Code. Gonna fix it and will give you an answer later on.

**Comment by charmaznable** [comment]
OK, wait for your good news

**Comment by TrueMB** [comment]
I fixed it, but I prefer not giving yet the new Version, since there are some new not finished features in it.
Might be released next Weekend.

You could add a shop category with the same ID for now. There should be no problem with that bypass. The plugin only looked 
 for Shop categories and not for the hotelcategories...
 
 So try using **/shop createcat <ID> 1 9 1m** (Creates a shop category for 1$ every minute)

**Comment by charmaznable** [comment]
OK, thank you. Now I disable the command to view empty rooms. I'll try again when you update next time.

**Comment by charmaznable** [comment]
By the way, I also found that the order to reset the guest room was invalid.

**Comment by TrueMB** [comment]
What exactly do you mean? Which Order and Guest Room = Hotelroom?

**Comment by charmaznable** [comment]
I use translation software to communicate with you. Maybe there is a problem with the translation. You're right. That's it.Hotelroom.

**Comment by TrueMB** [comment]
Is there an Error?
Or is something not working correctly?

**Comment by charmaznable** [comment]
There was no console error when using the command, but the hotel room was not reset.
 The worldedit I use is fawe

**Comment by TrueMB** [comment]
I am pretty sure the Issue is FAWE then.... heard it was fixed, after using the normal WorldEdit.
Maybe I will add Support in the future for FAWE. The Plugin is sometimes just weird...

**Comment by charmaznable** [comment]
Well, fortunately, my hotel rooms are very monotonous. I can roll back my rooms with fawe.

**Comment by TrueMB** [comment]
50a043947afcb4a6a1428fd2700a80903276ab50

The Main Bug is fixed in there and will be released in the next Version. I will also look into FAWE Support and might add that as well.

**Comment by TrueMB** [comment]
I just tested FAWE and it seems to work with the newest Version.
